name: Pull Request
on:
  pull_request:
    types: [ready_for_review]
    branches:
      - 'develop'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1.5.2
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
      - name: Test
        run: ./gradlew :lib:jsNodeTest :lib:jsBrowserTest :lib:jvmTest
        env:
          GITHUB_ACTOR: ${{ secrets.PUBLISH_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}